Lesson 7
EvgenyNarel/HoumWorks pull request #3
Opened 2020-08-18 16:07 UTC by EvgenyNarel

2020-08-24 07:08 UTC, RomanKashenok requested changes

2020-08-24 07:08 UTC, RomanKashenok commented on src/Task_7/bankCards/CreditCards.java
> +public class CreditCards extends BankCard {
Class name should be not in plural form

2020-08-28 07:51 UTC, RomanKashenok approved these changes

2020-08-28 07:51 UTC, RomanKashenok commented on src/task_seven/appliance/Runner.java
>  //        ForBath washer = new ForBath("washer");
If you don't use code - remove it

2020-08-31 20:33 UTC, EvgenyNarel commented on src/task_seven/appliance/Runner.java
>  //        ForBath washer = new ForBath("washer");
I deleted something that is not used

2020-08-31 20:35 UTC, merged